In [1]:
import pandas as pd
import numpy as np

Importing the neccessary Library Files

In [2]:
df = pd.read_csv('Research_dataset.csv')

df.drop(df.columns[[0]], axis=1,inplace=True)

Importing the Data Set created earlier under the name of Research_dataset Dropping the column containing the Index as Index is re-made when the dataset is attached to the dataframe,hence avoiding duplication.

In [3]:
s = (1000,1000)

v = np.zeros(s)

val = pd.DataFrame(data=v)

Setting the dimensions of the Matrix as 1000 x 1000
Creating a Zero Matrix (Matrix composed of only Zeroes) of the the Dimensions Given Above
Creating a DataFrame from the Matrix Created above via Numpy

In [4]:
#df.drop(['Task', 'Active'], axis=1,inplace=True)
df.head()

,Active,Adaptibility,Ambition,Decisivness,Dominance,Emotional,Faith,Task
0,5,9,4,3,9,4,3,5
1,6,7,3,5,5,2,4,4
2,4,9,1,4,9,3,8,4
3,5,4,1,8,3,8,3,4
4,5,1,1,6,3,9,6,3

In [5]:
   
def func():
    for i in df.index:
        
        for j in df.index:
        
            x14 = y11 = df.iloc[i,1]      #Adaptibility
            x11 = y12 = df.iloc[i,2]      #Ambition
            x12 = y13 = df.iloc[i,3]      #Desicveness
            x13 = y14 = df.iloc[i,4]      #Dominance
            x15 = y15 = df.iloc[i,5]      #Emotional
            x16 = y16 = df.iloc[i,6]      #faith
        
            x24 = y21 = df.iloc[j,1]      #Adaptibility
            x21 = y22 = df.iloc[j,2]      #Ambition
            x22 = y23 = df.iloc[j,3]      #Desicveness
            x23 = y24 = df.iloc[j,4]      #Dominance
            x25 = y25 = df.iloc[j,5]      #Emotional
            x26 = y26 = df.iloc[j,6]      #faith
    
    
        
            if(df.iloc[i,7] >=5):
                
                if(df.iloc[i,0]>=5):
                    
                    forumla = ( (x11 + x12 + x13) + 30 - (x14 + x15 + x16) + 30 - (x21 + x22 + x23) + (x24 + x25 + x26) ) / (2*6*10.00)
                    val.loc[i,j] = forumla
                
                elif(df.iloc[i,0]<5):
                    forumla = ( 30 -(x11 + x12 + x13) + 30 - (x14 + x15 + x16) + (x21 + x22 + x23) + (x24 + x25 + x26) ) / (2*6*10.00)
                    val.loc[i,j] = forumla
        
            elif(df.iloc[i,7]<5):
                
                if(df.iloc[i,0]>=5):
                    forumla = ( (x11 + x12 + x13) + (x14 + x15 + x16) + 30 - (x21 + x22 + x23) + 30 - (x24 + x25 + x26) ) / (2*6*10.00)
                    val.loc[i,j] = forumla
            
                elif(df.iloc[i,0]<5):
                    forumla = (30 - (x11 + x12 + x13) + (x14 + x15 + x16) + (x21 + x22 + x23) + 30 - (x24 + x25 + x26) ) / (2*6*10.00)
                    val.loc[i,j] = forumla

Setting a function to calculate utility value for each

In [6]:
import time
start_time = time.time()
print(start_time)

func()

val.to_csv('Utility_val.csv')

end_time = time.time()
print("--- %s seconds ---" % ( end_time - start_time))

1490271878.8
--- 4670.15499997 seconds ---

In [7]:
val.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Columns: 1000 entries, 0 to 999
dtypes: float64(1000)
memory usage: 7.6 MB

In [9]:
val.describe()

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,...,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.0
mean,0.494392,0.501542,0.504008,0.506350,0.513542,0.504692,0.489583,0.509583,0.507967,0.506350,...,0.498392,0.506392,0.497500,0.509583,0.487200,0.510392,0.518392,0.491158,0.498392,0.0
std,0.069310,0.070384,0.085898,0.073689,0.082526,0.086330,0.066930,0.084888,0.077736,0.073689,...,0.072369,0.082658,0.084688,0.084888,0.069319,0.089408,0.105095,0.067616,0.072369,0.0
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
25%,0.441667,0.458333,0.433333,0.450000,0.458333,0.483333,0.441667,0.441667,0.441667,0.450000,...,0.441667,0.441667,0.466667,0.441667,0.441667,0.441667,0.441667,0.450000,0.441667,0.0
50%,0.487500,0.508333,0.491667,0.516667,0.516667,0.525000,0.475000,0.491667,0.508333,0.516667,...,0.491667,0.487500,0.508333,0.491667,0.475000,0.483333,0.466667,0.487500,0.491667,0.0
75%,0.550000,0.550000,0.583333,0.566667,0.583333,0.558333,0.533333,0.591667,0.575000,0.566667,...,0.558333,0.583333,0.550000,0.591667,0.533333,0.600000,0.633333,0.525000,0.558333,0.0
max,0.658333,0.658333,0.691667,0.666667,0.691667,0.675000,0.683333,0.700000,0.683333,0.666667,...,0.658333,0.691667,0.700000,0.700000,0.683333,0.708333,0.741667,0.691667,0.658333,0.0