In [1]:
import pandas as pd
import numpy as np

# Importing Main Libraries into the IPython Notebook

## More specifically NUMPY and PANDAS

In [2]:
df = pd.read_csv('Research_dataset.csv')

### Reading the csv file for obtaining the data and storing it in a Data Frame for further proccessing

In [3]:
df.drop(df.columns[[0]], axis=1,inplace=True)

### Apparently the redundant index has managed to creep in inspite of taking precautions to remove it earlier.

## We drop the Index column to obtain a clean Data Frame

In [4]:
s = (1000,1000)

v = np.zeros(s)

val = pd.DataFrame(data=v)

## Creating a 1000 X 1000 matrix just so we can store the distance values for Each Entry vs Each Entry ( 1000 Entries are present ! )

### Initialize it to Zero, and we would replace it with optimum values

### The Matrix is converted as NUMPY 2D array composed of all zeros of dimension 1000 X 1000

### The 2D NUMPY Array is then converted to a PANDAS Data Frame

In [5]:
df.head()

   Adaptibility  Ambition  Decisivness  Dominance  Emotional  Faith
0             1         7            8          5          3      6
1             1         9            3          2          6      6
2             9         7            1          2          8      5
3             7         4            6          3          4      6
4             3         3            5          7          4      2

In [6]:
def func():
    for i in df.index:
        
        for j in df.index:
        
            x14 = y11 = 10 - df.iloc[i,0]      #Adaptibility
            x11 = y12 = 10 - df.iloc[i,1]      #Ambition
            x12 = y13 = 10 - df.iloc[i,2]      #Desicveness
            x13 = y14 = 10 - df.iloc[i,3]      #Dominance
            x15 = y15 = 10 - df.iloc[i,4]      #Emotional
            x16 = y16 = 10 - df.iloc[i,5]      #faith
        
            x24 = y21 = df.iloc[j,0]      #Adaptibility
            x21 = y22 = df.iloc[j,1]      #Ambition
            x22 = y23 = df.iloc[j,2]      #Desicveness
            x23 = y24 = df.iloc[j,3]      #Dominance
            x25 = y25 = df.iloc[j,4]      #Emotional
            x26 = y26 = df.iloc[j,5]      #faith
        
            forumla = (y11-y21)*(y11-y21) + (y12-y22)*(y12-y22) + (y13-y23)*(y13-y23)+ (y14-y24)*(y14-y24) + (y15-y25)*(y15-y25) + (y16-y26)*(y16-y26); 
            val.loc[i,j] =  forumla**(1/2.0);

# Definining a function to calculate all possible values of the distances.

## We have defined the Distance Metric as Euclidean Distance in a 6 Dimensional Space

## The degree of closness is estimated by calculating the exact inverse of the entry present , and then finding the distance of the Entry being compared from the inverse of the First Entry.

To Give a better idea:

Entry 1: -->   10,5,6,7,2,3

Formula for calculating inverse of the entry :------> ( 10 - attribute_value)

therefore the inverse of Entry 1 :-----> (10-10)= 0, (10-5) = 5, (10-6) = 4, (10 - 7) = 3, (10 - 2) = 8, (10 - 3) = 7

i.e. Inverse(Entry 1) : ----->  0,5,4,3,8,7
     Orignal(Entry 1) : -----> 10,5,6,7,2,3
     
     Now we calculate the Euclidean Distance of Entry 2 from Inverse(Entry 1) on the 6 Dimensional Vector Space
     
          Euclidean Distance :------>     SquareRoot(Sum(Square(Attribute(Inverse(Entry1))-Attribute(Entry 2))))

In [7]:
import time
start_time = time.time()
print(start_time)

func()

val.to_csv('Utility_val.csv')

end_time = time.time()
print("--- %s seconds ---" % ( end_time - start_time))

1492449167.58
--- 4194.29699993 seconds ---

In [8]:
val.head()

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
0,11.661904,10.723805,5.291503,6.164414,7.874008,5.830952,9.327379,9.380832,8.944272,10.908712,...,7.937254,7.000000,9.539392,5.477226,9.110434,10.049876,8.944272,7.681146,6.000000,0.0
1,10.723805,13.711309,11.180340,6.557439,7.000000,9.110434,11.489125,9.433981,5.916080,11.575837,...,7.874008,10.954451,7.615773,9.539392,8.602325,9.591663,7.280110,11.135529,7.681146,0.0
2,5.291503,11.180340,14.696938,8.717798,5.830952,12.328828,10.344080,10.770330,8.366600,7.549834,...,8.544004,13.076697,7.549834,11.747340,9.848858,7.937254,9.591663,11.445523,11.489125,0.0
3,6.164414,6.557439,8.717798,6.928203,4.242641,7.071068,7.141428,8.602325,9.165151,6.244998,...,7.416198,8.185353,9.000000,5.656854,9.110434,5.744563,10.198039,4.795832,7.071068,0.0
4,7.874008,7.000000,5.830952,4.242641,9.380832,5.291503,9.110434,4.000000,10.000000,7.810250,...,7.416198,4.795832,8.660254,7.745967,7.280110,6.708204,7.348469,9.643651,6.782330,0.0

In [9]:
val.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Columns: 1000 entries, 0 to 999
dtypes: float64(1000)
memory usage: 7.6 MB

In [10]:
val.describe()

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,...,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.0
mean,8.443504,9.113710,9.343901,7.005252,7.735447,8.410218,9.118018,8.788689,9.216241,8.427545,...,7.886389,8.843783,9.295218,8.183200,8.686891,8.108164,9.383804,9.059195,8.225194,0.0
std,1.968276,2.129041,2.200306,1.641382,1.878133,2.073050,2.130794,2.142086,2.244757,2.004622,...,2.056965,2.137304,2.131073,1.995550,2.164396,1.954864,2.166544,2.134840,2.038956,0.0
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
25%,7.071068,7.745967,7.937254,5.916080,6.557439,7.000000,7.810250,7.416198,7.745967,7.071068,...,6.557439,7.483315,8.000000,6.855655,7.211103,6.782330,7.937254,7.681146,6.782330,0.0
50%,8.544004,9.219544,9.407406,7.071068,7.874008,8.602325,9.219544,8.944272,9.327379,8.602325,...,8.000000,8.916233,9.539392,8.246211,8.717798,8.246211,9.513112,9.219544,8.366600,0.0
75%,9.797959,10.723805,10.908712,8.185353,9.110434,9.899495,10.641879,10.198039,10.816654,9.848858,...,9.486833,10.344080,10.770330,9.591663,10.295630,9.433981,10.965838,10.583005,9.746794,0.0
max,14.071247,14.594520,15.811388,11.832160,12.922848,14.387495,14.422205,14.177447,15.937377,13.453624,...,13.674794,14.142136,14.628739,14.282857,15.000000,13.114877,14.933185,14.560220,14.212670,0.0